### ISSUE TITLE
Foreign aid can be countered, but not challenged

### ISSUE THREAD

**Issue by timleslie** [Thinkmill/code-challenge#2]
https://github.com/Thinkmill/code-challenge/blob/d9f2e745d160f2a30bba28b47b58ff9f9361263e/201808/index.js#L351

The code currently has `foreign-aid` as an action which can be challenged, but not countered. It should be the other way round.

```
		if( action === 'taking-3' || action === 'assassination' || action === 'stealing' || action === 'swapping' ) {
			const cards = {
				'taking-3': 'duke',
				'assassination': 'assassin',
				'stealing': 'captain',
				'swapping': 'ambassador',
			};

			const _hasBeenChallenged = this.ChallengeRound({ player, card: cards[ action ], action, type: 'challenge-round' });
			if( _hasBeenChallenged && _hasBeenChallenged !== 'done' ) {
				return;
			}
		}

		if( action === 'assassination' || action === 'stealing' || 'foreign-aid' ) {
			const cards = {
				'assassination': 'contessa',
				'stealing': [ 'captain', 'ambassador' ],
				'foreign-aid': 'duke',
			};
```

**Comment by timleslie** [comment]
Let me try to show an example of why I think it's more than just a semantic problem. This is a game from a simulation I ran.

```
🃏  [exampleBot1 ♥♥ 💰 0] takes 3 coins with the duke
🃏  [exampleBot2 ♥♥ 💰 0] takes 2 coins foreign aid
❓  [exampleBot2 ♥♥ 💰 0] was challenged by [exampleBot1 ♥♥ 💰 3]
🚨  [exampleBot2 ♥♥ 💰 0] was penalised because of lying
💔  [exampleBot2 ♥ 💰 0] has lost the contessa
```

In this case, `bot2` tried to take foreign aid. He was `challenged`, and subsequently lost a card because he didn't hold a `duke`. This isn't what should happen here. If `bot2` has a `duke`, he can use that to block `bot1`, but there should be no way that `bot1` ever loses a card for trying to take foreign aid.

Also, in this case, if `bot2` has a `duke` and tries to block `bot1`, then `bot1` (or anyone else) should have the opportunity to challenge this counter action (i.e., to call bullshit on `bot2` having the blocking `duke`). In the currently implemented engine, there is no challenge round available for this to happen.

I think foreign-aid blocking needs to happen within the current counter action handler, and the logic of that part of the engine needs to be extended to allow anyone the opportunity to block in this case (and then for anyone to subsequently challenge that action).

**Comment by dominikwilkowski** [comment]
Fair call... more work... yay!

**Comment by dominikwilkowski** [comment]
So below are the different combinations of things that can happen on each action. I will write tests for each first and then change the algo. It's getting pretty complicated :)

- taking-1
	"`taking-1`"
	=> do-the-thing
----
- couping
	"`couping`"
	=> do-the-thing
----
- taking-3 no OnChallengeActionRound
	"`taking-3` without challenge"
	=> do-the-thing
- taking-3 successful OnChallengeActionRound
	"`taking-3` with successful challenge"
	=> no effect, penalty(player)
- taking-3 unsuccessful OnChallengeActionRound
	"`taking-3` with unsuccessful challenge"
	=> do-the-thing, penalty(challenger), swapCard(player)
----
- assassination no OnChallengeActionRound, no OnCounterAction
	"`assassination` without challenge or counter action"
	=> do-the-thing
- assassination successful OnChallengeActionRound
	"`assassination` with successful challenge"
	=> no effect, penalty(player)
- assassination unsuccessful OnChallengeActionRound
	"`assassination` with unsuccessful challenge"
	=> do-the-thing, penalty(challenger), swapCard(player)
- assassination no OnChallengeActionRound, OnCounterAction, no OnCounterActionRound
	"`assassination` with counter action but no counter challenge"
	=> no effect
- assassination no OnChallengeActionRound, OnCounterAction, successful OnCounterActionRound
	"`assassination` with counter action and successful counter challenge"
	=> do-the-thing, penalty(target)
- assassination no OnChallengeActionRound, OnCounterAction, unsuccessful OnCounterActionRound
	"`assassination` with counter action and unsuccessful counter challenge"
	=> no effect, penalty(player), swapCard(target)
----
- stealing no OnChallengeActionRound, no OnCounterAction
	"`stealing` without challenge or counter action"
	=> do-the-thing
- stealing successful OnChallengeActionRound
	"`stealing` with successful challenge"
	=> no effect, penalty(player)
- stealing unsuccessful OnChallengeActionRound
	"`stealing` with unsuccessful challenge"
	=> do-the-thing, penalty(challenger), swapCard(player)
- stealing no OnChallengeActionRound, OnCounterAction, no OnCounterActionRound
	"`stealing` with counter action but no counter challenge"
	=> no effect
- stealing no OnChallengeActionRound, OnCounterAction, successful OnCounterActionRound
	"`stealing` with counter action and successful counter challenge"
	=> do-the-thing, penalty(target)
- stealing no OnChallengeActionRound, OnCounterAction, unsuccessful OnCounterActionRound
	"`stealing` with counter action and unsuccessful counter challenge"
	=> no effect, penalty(player), swapCard(target)
----
- swapping no OnChallengeActionRound
	"`swapping` without challenge"
	=> do-the-thing
- swapping successful OnChallengeActionRound
	"`swapping` with successful challenge"
	=> no effect, penalty(player)
- swapping unsuccessful OnChallengeActionRound
	"`swapping` with unsuccessful challenge"
	=> do-the-thing, penalty(challenger), swapCard(player)
----
- foreign-aid no OnCounterAction
	"`foreign-aid` without counter action"
	=> do-the-thing
- foreign-aid OnCounterAction, successful OnCounterActionRound
	"`foreign-aid` with counter action and successful counter challenge"
	=> do-the-thing, penalty(challenger)
- foreign-aid OnCounterAction, unsuccessful OnCounterActionRound
	"`foreign-aid` with counter action and unsuccessful counter challenge"
	=> no effect, penalty(challenger), swapCard(target)

That's with the below algo:
```
if( taking-3, assassination, stealing, swapping )
	ChallengeRound via all bot.OnChallengeActionRound
		? false = continue
		: true = stop

if( foreign-aid, assassination, stealing )
	CounterAction via bot.OnCounterAction
		? false = continue
		: true = CounterChallengeRound via bot.OnCounterActionRound
			? false = continue
			: true = stop
```
