### ISSUE TITLE
Add description to the name of challenges

### ISSUE THREAD

**Issue by Noviny** [Thinkmill/code-challenge#32]
Would be great to give each challenge a name, and use that in the name of the challenge's folder. It makes walking the project from the command line nicer.

Pls close if you donotwant this.

**Comment by dominikwilkowski** [comment]
don't we add folders per challenge in each challenge folder?

**Comment by Noviny** [comment]
There are folders but 2018082 doesn't really tell me much. 2018-08-2 would be better, but 2018-08-2-sort-challenge would be great because when there are ten of these I can glance at the folders and immediately find the challenge I was looking for.

**Comment by dominikwilkowski** [comment]
Good idea. For next challenge will add :)
